# Generated by Django 4.1.7 on 2023-04-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(default='Airline', max_length=36)),
                ('flight_date', models.DateField(auto_now_add=True)),
                ('source', models.CharField(default='City', max_length=20)),
                ('destination', models.CharField(default='City', max_length=20)),
                ('route', models.CharField(blank=True, max_length=256, null=True)),
                ('dep_time', models.TimeField(auto_now_add=True)),
                ('arrival_time', models.TimeField(auto_now_add=True)),
                ('duration', models.TimeField(auto_now_add=True)),
                ('total_stops', models.CharField(default='non-stop', max_length=16)),
                ('additional_info', models.CharField(default='No info', max_length=36)),
            ],
        ),
    ]
