# Generated by Django 4.1.7 on 2023-04-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='dep_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_date',
            field=models.DateField(),
        ),
    ]
