# Generated by Django 4.1.7 on 2023-04-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_alter_flight_arrival_time_alter_flight_dep_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='dep_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='source',
            field=models.DateTimeField(default='City', max_length=20),
        ),
    ]
