# Generated by Django 4.1.7 on 2023-04-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_alter_flight_arrival_time_alter_flight_dep_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='source',
            field=models.CharField(default='City', max_length=20),
        ),
    ]
