# Generated by Django 4.1.7 on 2023-04-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_alter_flight_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.CharField(default='Time', max_length=8),
        ),
        migrations.AlterField(
            model_name='flight',
            name='dep_time',
            field=models.CharField(default='Time', max_length=8),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_date',
            field=models.CharField(default='Date', max_length=24),
        ),
    ]
