# Generated by Django 4.1.7 on 2023-04-24 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_alter_flight_arrival_time_alter_flight_dep_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flight',
        ),
    ]
