# Generated by Django 4.1.7 on 2023-04-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flight', '0006_delete_flight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(default='Airline', max_length=24)),
                ('date_of_journey', models.DateTimeField()),
                ('source', models.CharField(default='Source', max_length=16)),
                ('destination', models.CharField(default='Destination', max_length=16)),
                ('route', models.CharField(blank=True, max_length=256, null=True)),
                ('dep_time', models.CharField(default='00:00', max_length=5)),
                ('arrival_time', models.CharField(default='00:00', max_length=5)),
                ('duration', models.CharField(default='0h 0m', max_length=16)),
                ('total_stops', models.CharField(default='non-stop', max_length=16)),
                ('additional_info', models.CharField(blank=True, default='No info', max_length=16)),
            ],
        ),
    ]
